// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ip.proto

package ip

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet struct {
	PacketId string `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Packet_Error
	//	*Packet_CreateRoom
	//	*Packet_JoinRoom
	//	*Packet_LeaveRoom
	//	*Packet_Room
	//	*Packet_Player
	//	*Packet_JoinLeave
	//	*Packet_DataSend
	//	*Packet_RoomMessage
	//	*Packet_InviteFriend
	//	*Packet_StartGame
	Message              isPacket_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetPacketId() string {
	if m != nil {
		return m.PacketId
	}
	return ""
}

type isPacket_Message interface {
	isPacket_Message()
}

type Packet_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Packet_CreateRoom struct {
	CreateRoom *CreateRoom `protobuf:"bytes,3,opt,name=create_room,json=createRoom,proto3,oneof"`
}

type Packet_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,4,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Packet_LeaveRoom struct {
	LeaveRoom *LeaveRoom `protobuf:"bytes,5,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type Packet_Room struct {
	Room *Room `protobuf:"bytes,6,opt,name=room,proto3,oneof"`
}

type Packet_Player struct {
	Player *Player `protobuf:"bytes,7,opt,name=player,proto3,oneof"`
}

type Packet_JoinLeave struct {
	JoinLeave *JoinLeave `protobuf:"bytes,8,opt,name=join_leave,json=joinLeave,proto3,oneof"`
}

type Packet_DataSend struct {
	DataSend *DataSend `protobuf:"bytes,9,opt,name=data_send,json=dataSend,proto3,oneof"`
}

type Packet_RoomMessage struct {
	RoomMessage *RoomMessage `protobuf:"bytes,10,opt,name=room_message,json=roomMessage,proto3,oneof"`
}

type Packet_InviteFriend struct {
	InviteFriend *InviteFriend `protobuf:"bytes,11,opt,name=invite_friend,json=inviteFriend,proto3,oneof"`
}

type Packet_StartGame struct {
	StartGame *StartGame `protobuf:"bytes,12,opt,name=start_game,json=startGame,proto3,oneof"`
}

func (*Packet_Error) isPacket_Message() {}

func (*Packet_CreateRoom) isPacket_Message() {}

func (*Packet_JoinRoom) isPacket_Message() {}

func (*Packet_LeaveRoom) isPacket_Message() {}

func (*Packet_Room) isPacket_Message() {}

func (*Packet_Player) isPacket_Message() {}

func (*Packet_JoinLeave) isPacket_Message() {}

func (*Packet_DataSend) isPacket_Message() {}

func (*Packet_RoomMessage) isPacket_Message() {}

func (*Packet_InviteFriend) isPacket_Message() {}

func (*Packet_StartGame) isPacket_Message() {}

func (m *Packet) GetMessage() isPacket_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Packet) GetError() *Error {
	if x, ok := m.GetMessage().(*Packet_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Packet) GetCreateRoom() *CreateRoom {
	if x, ok := m.GetMessage().(*Packet_CreateRoom); ok {
		return x.CreateRoom
	}
	return nil
}

func (m *Packet) GetJoinRoom() *JoinRoom {
	if x, ok := m.GetMessage().(*Packet_JoinRoom); ok {
		return x.JoinRoom
	}
	return nil
}

func (m *Packet) GetLeaveRoom() *LeaveRoom {
	if x, ok := m.GetMessage().(*Packet_LeaveRoom); ok {
		return x.LeaveRoom
	}
	return nil
}

func (m *Packet) GetRoom() *Room {
	if x, ok := m.GetMessage().(*Packet_Room); ok {
		return x.Room
	}
	return nil
}

func (m *Packet) GetPlayer() *Player {
	if x, ok := m.GetMessage().(*Packet_Player); ok {
		return x.Player
	}
	return nil
}

func (m *Packet) GetJoinLeave() *JoinLeave {
	if x, ok := m.GetMessage().(*Packet_JoinLeave); ok {
		return x.JoinLeave
	}
	return nil
}

func (m *Packet) GetDataSend() *DataSend {
	if x, ok := m.GetMessage().(*Packet_DataSend); ok {
		return x.DataSend
	}
	return nil
}

func (m *Packet) GetRoomMessage() *RoomMessage {
	if x, ok := m.GetMessage().(*Packet_RoomMessage); ok {
		return x.RoomMessage
	}
	return nil
}

func (m *Packet) GetInviteFriend() *InviteFriend {
	if x, ok := m.GetMessage().(*Packet_InviteFriend); ok {
		return x.InviteFriend
	}
	return nil
}

func (m *Packet) GetStartGame() *StartGame {
	if x, ok := m.GetMessage().(*Packet_StartGame); ok {
		return x.StartGame
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_Error)(nil),
		(*Packet_CreateRoom)(nil),
		(*Packet_JoinRoom)(nil),
		(*Packet_LeaveRoom)(nil),
		(*Packet_Room)(nil),
		(*Packet_Player)(nil),
		(*Packet_JoinLeave)(nil),
		(*Packet_DataSend)(nil),
		(*Packet_RoomMessage)(nil),
		(*Packet_InviteFriend)(nil),
		(*Packet_StartGame)(nil),
	}
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Player struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string            `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Avatar               string            `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sid                  string            `protobuf:"bytes,6,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Player) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Player) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Player) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type Room struct {
	RoomId               string            `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomType             string            `protobuf:"bytes,2,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	Players              []*Player         `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{3}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *Room) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

func (m *Room) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Room) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateRoom struct {
	RoomType             string   `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoom) Reset()         { *m = CreateRoom{} }
func (m *CreateRoom) String() string { return proto.CompactTextString(m) }
func (*CreateRoom) ProtoMessage()    {}
func (*CreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{4}
}

func (m *CreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoom.Unmarshal(m, b)
}
func (m *CreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoom.Marshal(b, m, deterministic)
}
func (m *CreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoom.Merge(m, src)
}
func (m *CreateRoom) XXX_Size() int {
	return xxx_messageInfo_CreateRoom.Size(m)
}
func (m *CreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoom proto.InternalMessageInfo

func (m *CreateRoom) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

type LeaveRoom struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomType             string   `protobuf:"bytes,2,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom) Reset()         { *m = LeaveRoom{} }
func (m *LeaveRoom) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom) ProtoMessage()    {}
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{5}
}

func (m *LeaveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom.Unmarshal(m, b)
}
func (m *LeaveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom.Marshal(b, m, deterministic)
}
func (m *LeaveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom.Merge(m, src)
}
func (m *LeaveRoom) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom.Size(m)
}
func (m *LeaveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom proto.InternalMessageInfo

func (m *LeaveRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *LeaveRoom) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

type JoinRoom struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomType             string   `protobuf:"bytes,2,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom) Reset()         { *m = JoinRoom{} }
func (m *JoinRoom) String() string { return proto.CompactTextString(m) }
func (*JoinRoom) ProtoMessage()    {}
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{6}
}

func (m *JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom.Unmarshal(m, b)
}
func (m *JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom.Marshal(b, m, deterministic)
}
func (m *JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom.Merge(m, src)
}
func (m *JoinRoom) XXX_Size() int {
	return xxx_messageInfo_JoinRoom.Size(m)
}
func (m *JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom proto.InternalMessageInfo

func (m *JoinRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *JoinRoom) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

type JoinLeave struct {
	RoomId               string    `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Joins                []*Player `protobuf:"bytes,2,rep,name=joins,proto3" json:"joins,omitempty"`
	Leaves               []*Player `protobuf:"bytes,3,rep,name=leaves,proto3" json:"leaves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinLeave) Reset()         { *m = JoinLeave{} }
func (m *JoinLeave) String() string { return proto.CompactTextString(m) }
func (*JoinLeave) ProtoMessage()    {}
func (*JoinLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{7}
}

func (m *JoinLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinLeave.Unmarshal(m, b)
}
func (m *JoinLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinLeave.Marshal(b, m, deterministic)
}
func (m *JoinLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinLeave.Merge(m, src)
}
func (m *JoinLeave) XXX_Size() int {
	return xxx_messageInfo_JoinLeave.Size(m)
}
func (m *JoinLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinLeave.DiscardUnknown(m)
}

var xxx_messageInfo_JoinLeave proto.InternalMessageInfo

func (m *JoinLeave) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *JoinLeave) GetJoins() []*Player {
	if m != nil {
		return m.Joins
	}
	return nil
}

func (m *JoinLeave) GetLeaves() []*Player {
	if m != nil {
		return m.Leaves
	}
	return nil
}

// client to server
type DataSend struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	To                   []string `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Code                 int64    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	RoomType             string   `protobuf:"bytes,5,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataSend) Reset()         { *m = DataSend{} }
func (m *DataSend) String() string { return proto.CompactTextString(m) }
func (*DataSend) ProtoMessage()    {}
func (*DataSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{8}
}

func (m *DataSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSend.Unmarshal(m, b)
}
func (m *DataSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSend.Marshal(b, m, deterministic)
}
func (m *DataSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSend.Merge(m, src)
}
func (m *DataSend) XXX_Size() int {
	return xxx_messageInfo_DataSend.Size(m)
}
func (m *DataSend) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSend.DiscardUnknown(m)
}

var xxx_messageInfo_DataSend proto.InternalMessageInfo

func (m *DataSend) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *DataSend) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DataSend) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DataSend) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DataSend) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

// server to client
type RoomMessage struct {
	RoomType             string   `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Code                 int64    `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Time                 int64    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMessage) Reset()         { *m = RoomMessage{} }
func (m *RoomMessage) String() string { return proto.CompactTextString(m) }
func (*RoomMessage) ProtoMessage()    {}
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{9}
}

func (m *RoomMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMessage.Unmarshal(m, b)
}
func (m *RoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMessage.Marshal(b, m, deterministic)
}
func (m *RoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMessage.Merge(m, src)
}
func (m *RoomMessage) XXX_Size() int {
	return xxx_messageInfo_RoomMessage.Size(m)
}
func (m *RoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMessage proto.InternalMessageInfo

func (m *RoomMessage) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

func (m *RoomMessage) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RoomMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoomMessage) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RoomMessage) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type InviteFriend struct {
	RoomType             string   `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FromId               string   `protobuf:"bytes,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FriendId             string   `protobuf:"bytes,4,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteFriend) Reset()         { *m = InviteFriend{} }
func (m *InviteFriend) String() string { return proto.CompactTextString(m) }
func (*InviteFriend) ProtoMessage()    {}
func (*InviteFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{10}
}

func (m *InviteFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteFriend.Unmarshal(m, b)
}
func (m *InviteFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteFriend.Marshal(b, m, deterministic)
}
func (m *InviteFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteFriend.Merge(m, src)
}
func (m *InviteFriend) XXX_Size() int {
	return xxx_messageInfo_InviteFriend.Size(m)
}
func (m *InviteFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteFriend.DiscardUnknown(m)
}

var xxx_messageInfo_InviteFriend proto.InternalMessageInfo

func (m *InviteFriend) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

func (m *InviteFriend) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *InviteFriend) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *InviteFriend) GetFriendId() string {
	if m != nil {
		return m.FriendId
	}
	return ""
}

type StartGame struct {
	RoomType             string   `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGame) Reset()         { *m = StartGame{} }
func (m *StartGame) String() string { return proto.CompactTextString(m) }
func (*StartGame) ProtoMessage()    {}
func (*StartGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035787f70b0c50f, []int{11}
}

func (m *StartGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGame.Unmarshal(m, b)
}
func (m *StartGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGame.Marshal(b, m, deterministic)
}
func (m *StartGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGame.Merge(m, src)
}
func (m *StartGame) XXX_Size() int {
	return xxx_messageInfo_StartGame.Size(m)
}
func (m *StartGame) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGame.DiscardUnknown(m)
}

var xxx_messageInfo_StartGame proto.InternalMessageInfo

func (m *StartGame) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

func (m *StartGame) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func init() {
	proto.RegisterType((*Packet)(nil), "ip.Packet")
	proto.RegisterType((*Error)(nil), "ip.Error")
	proto.RegisterType((*Player)(nil), "ip.Player")
	proto.RegisterMapType((map[string]string)(nil), "ip.Player.AttributesEntry")
	proto.RegisterType((*Room)(nil), "ip.Room")
	proto.RegisterMapType((map[string]string)(nil), "ip.Room.MetadataEntry")
	proto.RegisterType((*CreateRoom)(nil), "ip.CreateRoom")
	proto.RegisterType((*LeaveRoom)(nil), "ip.LeaveRoom")
	proto.RegisterType((*JoinRoom)(nil), "ip.JoinRoom")
	proto.RegisterType((*JoinLeave)(nil), "ip.JoinLeave")
	proto.RegisterType((*DataSend)(nil), "ip.DataSend")
	proto.RegisterType((*RoomMessage)(nil), "ip.RoomMessage")
	proto.RegisterType((*InviteFriend)(nil), "ip.InviteFriend")
	proto.RegisterType((*StartGame)(nil), "ip.StartGame")
}

func init() { proto.RegisterFile("ip.proto", fileDescriptor_0035787f70b0c50f) }

var fileDescriptor_0035787f70b0c50f = []byte{
	// 750 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xef, 0x6a, 0xdb, 0x48,
	0x10, 0xb7, 0x64, 0x49, 0x96, 0xc6, 0x76, 0x12, 0x96, 0x23, 0x11, 0x39, 0x38, 0x1c, 0x91, 0x0f,
	0x39, 0x0e, 0x0c, 0x97, 0xbb, 0xd2, 0x92, 0x52, 0x68, 0xda, 0xa6, 0xb5, 0x4b, 0x53, 0xc2, 0xa6,
	0xdf, 0xcd, 0xc6, 0xda, 0x04, 0x39, 0xb6, 0x25, 0xa4, 0x8d, 0xa9, 0xfb, 0x1a, 0x7d, 0x86, 0x3e,
	0x51, 0x5f, 0xa5, 0x0f, 0x50, 0x66, 0x76, 0x25, 0xcb, 0x69, 0x53, 0xa8, 0xbf, 0xcd, 0x9f, 0xdf,
	0xec, 0xfe, 0x7e, 0xda, 0x99, 0x11, 0xf8, 0x49, 0xd6, 0xcf, 0xf2, 0x54, 0xa5, 0xcc, 0x4e, 0xb2,
	0xe8, 0x8b, 0x03, 0xde, 0x85, 0x18, 0xdf, 0x4a, 0xc5, 0xfe, 0x84, 0x20, 0x23, 0x6b, 0x94, 0xc4,
	0xa1, 0xd5, 0xb3, 0x8e, 0x02, 0xee, 0xeb, 0xc0, 0x30, 0x66, 0x07, 0xe0, 0xca, 0x3c, 0x4f, 0xf3,
	0xd0, 0xee, 0x59, 0x47, 0xed, 0xe3, 0xa0, 0x9f, 0x64, 0xfd, 0x33, 0x0c, 0x0c, 0x1a, 0x5c, 0x67,
	0xd8, 0xbf, 0xd0, 0x1e, 0xe7, 0x52, 0x28, 0x39, 0xca, 0xd3, 0x74, 0x16, 0x36, 0x09, 0xb8, 0x85,
	0xc0, 0x97, 0x14, 0xe6, 0x69, 0x3a, 0x1b, 0x34, 0x38, 0x8c, 0x2b, 0x8f, 0xfd, 0x03, 0xc1, 0x24,
	0x4d, 0xe6, 0xba, 0xc0, 0xa1, 0x82, 0x0e, 0x16, 0xbc, 0x4d, 0x93, 0xb9, 0x81, 0xfb, 0x13, 0x63,
	0xb3, 0x3e, 0xc0, 0x54, 0x8a, 0x85, 0x39, 0xde, 0x25, 0x74, 0x17, 0xd1, 0xef, 0x30, 0x6a, 0xe0,
	0xc1, 0xb4, 0x74, 0xd8, 0x5f, 0xe0, 0x10, 0xd2, 0x23, 0xa4, 0x8f, 0x48, 0x03, 0xa2, 0x38, 0x3b,
	0x04, 0x2f, 0x9b, 0x8a, 0xa5, 0xcc, 0xc3, 0x16, 0x21, 0x00, 0x11, 0x17, 0x14, 0x19, 0x34, 0xb8,
	0xc9, 0xe1, 0xad, 0x44, 0x91, 0xce, 0x0d, 0xfd, 0xd5, 0xad, 0xc8, 0x91, 0x6e, 0xc6, 0x5b, 0x27,
	0xa5, 0x83, 0x92, 0x62, 0xa1, 0xc4, 0xa8, 0x90, 0xf3, 0x38, 0x0c, 0x56, 0x92, 0x5e, 0x09, 0x25,
	0x2e, 0xe5, 0x3c, 0x46, 0x49, 0xb1, 0xb1, 0xd9, 0xff, 0xd0, 0x41, 0x2a, 0xa3, 0x99, 0x2c, 0x0a,
	0x71, 0x23, 0x43, 0x20, 0xfc, 0x76, 0x49, 0xf5, 0x5c, 0x87, 0x07, 0x0d, 0xde, 0xce, 0x57, 0x2e,
	0x7b, 0x0c, 0xdd, 0x64, 0xbe, 0x48, 0x94, 0x1c, 0x5d, 0xe7, 0x09, 0x5e, 0xd3, 0xa6, 0xb2, 0x1d,
	0x2c, 0x1b, 0x52, 0xe2, 0x35, 0xc5, 0x07, 0x0d, 0xde, 0x49, 0x6a, 0x3e, 0x6a, 0x29, 0x94, 0xc8,
	0xd5, 0xe8, 0x46, 0xcc, 0x64, 0xd8, 0x59, 0x69, 0xb9, 0xc4, 0xe8, 0x1b, 0x31, 0x23, 0x2d, 0x45,
	0xe9, 0xbc, 0x08, 0xa0, 0x65, 0x98, 0x45, 0x8f, 0xc0, 0xa5, 0xe7, 0x66, 0x0c, 0x9c, 0x71, 0x1a,
	0x4b, 0x6a, 0x90, 0x2e, 0x27, 0x9b, 0x85, 0x15, 0x8e, 0xda, 0x23, 0xe0, 0x55, 0xd9, 0x37, 0x0b,
	0x3c, 0xfd, 0x49, 0xd9, 0x16, 0xd8, 0x55, 0x5f, 0xd9, 0x49, 0x8c, 0x07, 0xcd, 0x91, 0x86, 0xae,
	0x20, 0x9b, 0x1d, 0x40, 0x27, 0x4e, 0x0a, 0xfc, 0xf2, 0x23, 0xca, 0x35, 0x29, 0xd7, 0x36, 0xb1,
	0xf7, 0x08, 0xd9, 0x05, 0x4f, 0x2c, 0x84, 0x12, 0x39, 0xf5, 0x4b, 0xc0, 0x8d, 0xc7, 0x4e, 0x00,
	0x84, 0x52, 0x79, 0x72, 0x75, 0xa7, 0x64, 0x11, 0xba, 0xbd, 0xe6, 0x51, 0xfb, 0x78, 0x7f, 0xf5,
	0xa2, 0xfd, 0xd3, 0x2a, 0x79, 0x36, 0x57, 0xf9, 0x92, 0xd7, 0xd0, 0x6c, 0x07, 0x9a, 0x45, 0x12,
	0x53, 0xa3, 0x04, 0x1c, 0xcd, 0xfd, 0x67, 0xb0, 0x7d, 0xaf, 0x00, 0x41, 0xb7, 0x72, 0x69, 0x04,
	0xa0, 0xc9, 0xfe, 0x00, 0x77, 0x21, 0xa6, 0x77, 0xa5, 0x04, 0xed, 0x9c, 0xd8, 0x4f, 0xac, 0xe8,
	0xab, 0x05, 0x0e, 0xf5, 0xe0, 0x1e, 0xb4, 0xe8, 0x81, 0x2b, 0xe5, 0x1e, 0xba, 0xc3, 0x18, 0x87,
	0x8d, 0x12, 0x6a, 0x99, 0x95, 0xf5, 0x3e, 0x06, 0x3e, 0x2c, 0x33, 0xc9, 0x0e, 0xa1, 0xa5, 0xbb,
	0xaf, 0x08, 0x9b, 0x24, 0xa4, 0xd6, 0x9a, 0xbc, 0x4c, 0xb1, 0x63, 0xf0, 0x67, 0x52, 0x09, 0x6c,
	0xa6, 0xd0, 0x21, 0xd8, 0x6e, 0xd9, 0x38, 0xfd, 0x73, 0x93, 0xd0, 0x5a, 0x2b, 0xdc, 0xfe, 0x53,
	0xe8, 0xae, 0xa5, 0x7e, 0x4b, 0xd5, 0xdf, 0x00, 0xab, 0x49, 0x5e, 0x57, 0x60, 0xad, 0x2b, 0x88,
	0x4e, 0x21, 0xa8, 0xa6, 0x72, 0xb3, 0x8f, 0x10, 0x3d, 0x07, 0xbf, 0x5c, 0x03, 0x1b, 0x9e, 0x30,
	0x81, 0xa0, 0x1a, 0xd2, 0x87, 0x8f, 0xe8, 0x81, 0x8b, 0xd3, 0x5b, 0x84, 0xf6, 0x0f, 0x9f, 0x5a,
	0x27, 0x58, 0x04, 0x1e, 0x4d, 0xff, 0xcf, 0x5e, 0xc3, 0x64, 0xa2, 0x8f, 0xe0, 0x97, 0x13, 0xfe,
	0xf0, 0x55, 0x0c, 0x1c, 0x7a, 0x2d, 0x24, 0xda, 0xe1, 0x64, 0xe3, 0x58, 0xa8, 0x94, 0x0e, 0x0e,
	0xb8, 0xad, 0xd2, 0x6a, 0xbe, 0xb0, 0xbb, 0x9b, 0x66, 0xbe, 0xd6, 0x54, 0xba, 0xf7, 0x54, 0x7e,
	0xb6, 0xa0, 0x5d, 0x5b, 0x16, 0xbf, 0x7c, 0x97, 0x3a, 0x35, 0xfb, 0x3e, 0xb5, 0xeb, 0xdc, 0x6c,
	0xed, 0x80, 0x93, 0x5d, 0xd1, 0x75, 0x6a, 0x74, 0x4b, 0x7a, 0x6e, 0x8d, 0x1e, 0x03, 0x47, 0x25,
	0x33, 0x49, 0xf3, 0xd3, 0xe4, 0x64, 0x47, 0x9f, 0xa0, 0x53, 0x5f, 0x45, 0x1b, 0xb2, 0xda, 0x83,
	0x16, 0x32, 0xc1, 0x84, 0x26, 0xe6, 0xa1, 0xab, 0xdf, 0x5d, 0xef, 0x3e, 0x4c, 0xe9, 0x45, 0xe0,
	0xeb, 0xc0, 0x30, 0xc6, 0xe6, 0xab, 0x16, 0xda, 0x66, 0x17, 0x5f, 0x79, 0xf4, 0x87, 0xfc, 0xef,
	0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x19, 0x12, 0xc2, 0x2d, 0x07, 0x00, 0x00,
}
